name: CFBanner
version: 1.9.3
author: CainFoool
main: me.cain.plugin.CFBanner
permissions:
  cfbanner.*:
    description: Allow everything
  cfbanner.allowfly:
    description: Allow users to fly
  cfbanner.allowcheat:
    description: Allow users to cheat
